### ISSUE TITLE
ECS broker with ECS Flex; Error creating bean with name 'ecsService'

### ISSUE THREAD

**Issue by keedya** [thecodeteam/ecs-cf-service-broker#163]
Using ECS flex, 
```
ecs-service-broker:
  namespace: "store"
  replicationGroup: "store"
  api:
    endpoint: "https://1.2.3.4:443"
  # Admin Access Details
  ecsConnection:
    endpoint: "https://1.2.3.5:4443"
    username: "root"
    password: "somethingelse"
```

the ECS broker returns the following error
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-20 14:42:37.448 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is org.springframework.cloud.servicebroker.exception.ServiceBrokerException: com.emc.ecs.servicebroker.EcsManagementClientException: Error: Method Not Allowed (6405): Method not allowed.. Retryable: false.
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at com.emc.ecs.servicebroker.config.Application.main(Application.java:38) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [app.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [app.jar:na]
Caused by: org.springframework.cloud.servicebroker.exception.ServiceBrokerException: com.emc.ecs.servicebroker.EcsManagementClientException: Error: Method Not Allowed (6405): Method not allowed.. Retryable: false.
        at com.emc.ecs.servicebroker.service.EcsService.createUser(EcsService.java:216) ~[classes!/:na]
        at com.emc.ecs.servicebroker.service.EcsService.prepareRepository(EcsService.java:400) ~[classes!/:na]
        at com.emc.ecs.servicebroker.service.EcsService.initialize(EcsService.java:75) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        ... 26 common frames omitted
Caused by: com.emc.ecs.servicebroker.EcsManagementClientException: Error: Method Not Allowed (6405): Method not allowed.. Retryable: false.
        at com.emc.ecs.management.sdk.Connection.handleResponse(Connection.java:223) ~[classes!/:na]
        at com.emc.ecs.management.sdk.Connection.handleRemoteCall(Connection.java:139) ~[classes!/:na]
        at com.emc.ecs.management.sdk.Connection.handleRemoteCall(Connection.java:132) ~[classes!/:na]
        at com.emc.ecs.management.sdk.ObjectUserAction.create(ObjectUserAction.java:19) ~[classes!/:na]
        at com.emc.ecs.servicebroker.service.EcsService.createUser(EcsService.java:211) ~[classes!/:na]
        ... 35 common frames omitted
```

**Comment by spiegela** [comment]
The issue here is that the broker creates a new Object User, and a User Secret when the `ecsService` starts up.  In ECS Flex, creation of these resources via management API requires an HTTP Header to override the default blocks: `X-EMC-Override: true`.

In the longer term, this won't be needed since we'll be able to create users through IAM, which shouldn't be blocked at all, but the broker will need to be updated for IAM an user-policy support anyhow.
