### ISSUE TITLE
Improve error messages for ECSService init

### ISSUE THREAD

**Issue by spiegela** [thecodeteam/ecs-cf-service-broker#60]
When the EcsService fails to start, it's typically because user configuration settings are incorrect, or the ECS management API is unavailable from the "management-endpoint"; however, the error message is cryptic. We need to improve the user experience for initial startup, and provide more meaningful errors.

**Comment by jasoncwik** [comment]
Another example: if your admin credentials are incorrect, the error message is buried in a big stack trace instead of simply printing an appropriate error message to the console.  This specific case should probably be explicitly handled.

```
ndencyException: Error creating bean with name 'serviceInstanceController' defined in URL [jar:file:/home/vcap/app/BOOT-INF/lib/spring-cloud-cloudfoundry-service-broker-1.0.1.RELEASE.jar!/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ecsServiceInstanceService': Unsatisfied dependency expressed through field 'ecs'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is com.emc.ecs.cloudfoundry.broker.EcsManagementClientException: Error: Unauthorized (401): Access is denied due to invalid or expired credentials. Retryable: null.
2018-03-15T13:48:41.915-07:00 [APP/PROC/WEB/0] [OUT] 2018-03-15 20:48:41.915 INFO 15 --- [ main] utoConfigurationReportLoggingInitializer :
2018-03-15T13:48:41.915-07:00 [APP/PROC/WEB/0] [OUT] Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] 2018-03-15 20:48:41.926 ERROR 15 --- [ main] o.s.boot.SpringApplication : Application startup failed
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceInstanceController' defined in URL [jar:file:/home/vcap/app/BOOT-INF/lib/spring-cloud-cloudfoundry-service-broker-1.0.1.RELEASE.jar!/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ecsServiceInstanceService': Unsatisfied dependency expressed through field 'ecs'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is com.emc.ecs.cloudfoundry.broker.EcsManagementClientException: Error: Unauthorized (401): Access is denied due to invalid or expired credentials. Retryable: null.
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at com.emc.ecs.cloudfoundry.broker.config.Application.main(Application.java:44) [classes/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ecsServiceInstanceService': Unsatisfied dependency expressed through field 'ecs'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is com.emc.ecs.cloudfoundry.broker.EcsManagementClientException: Error: Unauthorized (401): Access is denied due to invalid or expired credentials. Retryable: null.
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] ... 27 common frames omitted
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is com.emc.ecs.cloudfoundry.broker.EcsManagementClientException: Error: Unauthorized (401): Access is denied due to invalid or expired credentials. Retryable: null.
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] ... 41 common frames omitted
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] Caused by: com.emc.ecs.cloudfoundry.broker.EcsManagementClientException: Error: Unauthorized (401): Access is denied due to invalid or expired credentials. Retryable: null.
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at com.emc.ecs.management.sdk.Connection.handleResponse(Connection.java:201) ~[classes/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at com.emc.ecs.management.sdk.Connection.login(Connection.java:115) ~[classes/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at com.emc.ecs.management.sdk.Connection.makeRemoteCall(Connection.java:148) ~[classes/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at com.emc.ecs.management.sdk.Connection.handleRemoteCall(Connection.java:132) ~[classes/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at com.emc.ecs.management.sdk.ReplicationGroupAction.list(ReplicationGroupAction.java:25) ~[classes/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at com.emc.ecs.cloudfoundry.broker.service.EcsService.lookupReplicationGroupID(EcsService.java:278) ~[classes/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at com.emc.ecs.cloudfoundry.broker.service.EcsService.initialize(EcsService.java:59) ~[classes/:na]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2018-03-15T13:48:41.927-07:00 [APP/PROC/WEB/0] [OUT] ... 53 common frames omitted
2018-03-15T13:49:35.995-07:00 [CELL/0] [ERR] Failed to make TCP connection to port 8080: connection refused
2018-03-15T13:49:35.995-07:00 [CELL/0] [ERR] Timed out after 1m0s: health check never passed.
2018-03-15T13:49:35.997-07:00 [CELL/0] [OUT] Exit status 0
2018-03-15T13:49:36.339-07:00 [APP/PROC/WEB/0] [OUT] Exit status 143
2018-03-15T13:49:36.345-07:00 [CELL/0] [OUT] Stopping instance b0fdad52-2047-495d-685e-fa34
2018-03-15T13:49:36.345-07:00 [CELL/0] [OUT] Destroying container
2018-03-15T13:49:36.362-07:00 [API/0] [OUT] Process has crashed with type: "web"
2018-03-15T13:49:36.370-07:00 [API/0] [OUT] App instance exited with guid 1b0a2aca-a0de-4e7d-b773-73d000e7a791 payload: {"instance"=>"b0fdad52-2047-495d-685e-fa34", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"Instance never healthy after 1m0s: Failed to make TCP connection to port 8080: connection refused", "crash_count"=>103, "crash_timestamp"=>1521146976342601145, "version"=>"e9386eca-27ca-42a3-99a3-e765ceb3e0f5"}
2018-03-15T13:49:36.636-07:00 [CELL/0] [OUT] Successfully destroyed container
```
